name: RegularCI

on:
  push:

jobs:
  copy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Look Repository
        run: |
          ls
          cd movie-store-frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Build Step
        run: |
          npm -v
          npm install
          npm run lint
          npm run build