name: RegularCI

on:
  push:

jobs:
  copy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Github Repository
        run: |
          git init
          git remote add origin "https://github.com/artlavre/MovieStore-Frontend.git"
          git fetch origin
          git checkout master
      - name: Look Repository
        run: |
          ls
          cd movie-store-frontend
          ls
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Build Step
        run: |
          cd movie-store-frontend
          npm -v
          npm install
          npm run lint
          npm run build